#!/bin/bash -e

cd $(dirname $0)/..

source $(dirname $0)/version

declare -A OS_ARCH_ARG

OS_PLATFORM_ARG=(linux windows darwin)
OS_ARCH_ARG[linux]="amd64 arm arm64"
OS_ARCH_ARG[windows]="386 amd64"
OS_ARCH_ARG[darwin]="amd64 arm64"

go generate
if [ -n "$CROSS" ]; then
    rm -rf bin
    mkdir -p bin
    for OS in ${OS_PLATFORM_ARG[@]}; do
        for ARCH in ${OS_ARCH_ARG[${OS}]}; do
            OUTPUT_BIN="bin/rancher-compose_$OS-$ARCH"
            if test "$OS" = "windows"; then
                OUTPUT_BIN="${OUTPUT_BIN}.exe"
            fi
            echo "Building binary for $OS/$ARCH..."
            GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
                  -ldflags="-w -X github.com/rancher/rancher-compose/version.VERSION=$VERSION" \
                  -o ${OUTPUT_BIN} ./
        done
    done
else
    go build -ldflags="-w -X github.com/rancher/rancher-compose/version.VERSION=$VERSION" -o bin/rancher-compose
fi

if [ ! -e bin/rancher-compose-executor ]; then
    ln -s rancher-compose bin/rancher-compose-executor
fi
